# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
channels = ["conda-forge", "bioconda"]
name = "pypsa-eur"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.10"
pip = "*"
pypsa = ">=0.35.2"
atlite = ">=0.3"
linopy = ">=0.4.4"
powerplantmatching = ">=0.5.15"
dask = "*"
xlrd = "*"
openpyxl = "*"
seaborn = "*"
snakemake-minimal = ">=9"
snakemake-storage-plugin-http = ">=0.3"
snakemake-executor-plugin-slurm = "*"
snakemake-executor-plugin-cluster-generic = "*"
memory_profiler = "*"
yaml = "*"
pytables = "*"
lxml = "*"
numpy = "*"
pandas = ">=2.1"
geopandas = ">=1"
xarray = ">=2024.3.0,<2025.7.0"
rioxarray = "*"
netcdf4 = "*"
libgdal-netcdf = "*"
networkx = "*"
scipy = "*"
glpk = "*"
shapely = ">=2.0"
matplotlib = "*"
proj = "*"
fiona = "*"
country_converter = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
jpype1 = "*"
pyxlsb = "*"
graphviz = "*"
geojson = "*"
copernicusmarine = "*"
pyscipopt = "*"
plotly = "*"
bokeh = "*"
folium = "*"
cartopy = "*"
descartes = "*"
rasterio = "*"
jupyter = "*"
ipython = "*"
pre-commit = "*"
ruff = "*"
pylint = "*"
typer = "*"
python-dotenv = "*"

[pypi-dependencies]
gurobipy = "*"
highspy = "*"
tsam = ">=2.3.1"
entsoe-py = "*"
snakemake-storage-plugin-cached-http = { git = "https://github.com/PyPSA/snakemake-storage-plugin-cached-http.git" }
