version = 1
SPDX-PackageName = "Open-TYDNP"
SPDX-PackageSupplier = "Open Energy Transition gGmbH <tyndp@openenergytransition.org>"
SPDX-PackageOriginator = "Tom Brown <t.brown@tu-berlin.de>"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/open-tyndp"

[[annotations]]
path = [
    "data/**",
    "doc/configtables/*",
    "doc/data.csv",
    "doc/img/*",
    "test/test_data/*",
]
SPDX-FileCopyrightText = [
    "The Open-TYNDP Authors",
    "The PyPSA-Eur Authors",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "data/tyndp_technology_map.csv",
    "doc/configtables/benchmarking.csv",
    "doc/img/tyndp/*",
]
SPDX-FileCopyrightText = [
    "The Open-TYNDP Authors",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    ".github/**",
    "borg-it",
    "envs/*.lock.yaml",
    "matplotlibrc",
]
SPDX-FileCopyrightText = [
    "The Open-TYNDP Authors",
    "The PyPSA-Eur Authors",
]
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "report/**",
]
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "MIT"
