# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

benchmarking:
  enable: false
  remove_last_day: true

  tables:
    final_energy_demand:
      table_type: scenario_comparison
      sheet_name: 5-
      unit: TWh
      index_col: 2
      header: [4, 5]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        AC: electricity
        AC_OH: electricity
        low voltage: electricity
        H2: hydrogen
        exogenous gas demand: methane
        oil: liquids
        kerosene for aviation: liquids
        shipping oil: liquids
        land transport oil: liquids
        coal: solids

    elec_demand:
      table_type: scenario_comparison
      sheet_name: 23-
      unit: TWh
      index_col: [2, 3]
      header: 4
      names:
        index:
        - scenario
        - year
        column:
        - carrier
      mapping:
        electricity: final demand (inc. t&d losses, excl. pump storage )

    methane_demand:
      table_type: scenario_comparison
      sheet_name: 8-
      unit: TWh
      index_col: 2
      header: [4, 5]
      nrows: 15
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        CCGT: power generation
        OCGT: power generation
        gas-ccgt: power generation
        gas-ccgt-ccs: power generation
        gas-ocgt: power generation
        gas-conv: power generation
        SMR: smr
        SMR CC: smr
        exogenous gas demand: total (excl. SMR and power generation)

    hydrogen_demand:
      table_type: scenario_comparison
      sheet_name: 54-
      unit: TWh
      index_col: [2, 3]
      header: 4
      names:
        index:
        - year
        - scenario
        column:
        - carrier
      mapping:
        Fischer-Tropsch: e-fuels production
        H2 for industry: industry
        H2 turbine: electricity generation and heat production
        h2-ccgt: electricity generation and heat production
        h2-fuel-cell: electricity generation and heat production
        Sabatier: e-fuels production
        methanolisation: e-fuels production
        H2 for shipping: international shipping

    power_capacity:
      table_type: scenario_comparison
      sheet_name: 25-
      unit: GW
      index_col: [2, 3]
      header: 4
      nrows: 10
      ncolumns: 17
      names:
        index:
        - scenario
        - year
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        offwind-h2-fb-oh: wind offshore
        offwind-h2-fl-oh: wind offshore
        onwind: wind onshore
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: hydrogen
        h2-fuel-cell: hydrogen
        coal: coal + other fossil
        coal+ccs: coal + other fossil
        lignite: coal + other fossil
        lignite+ccs: coal + other fossil
        oil-heavy: oil
        oil-light: oil
        oil-shale: oil
        gas-ccgt: methane
        gas-ccgt-ccs: methane
        gas-ocgt: methane
        gas-conv: methane
        battery discharger: battery
        home battery discharger: battery
        urban central solid biomass CHP: chp and small thermal
        PHS: hydro and pumped storage
        hydro: hydro and pumped storage
        ror: hydro and pumped storage

    power_generation:
      table_type: scenario_comparison
      sheet_name: 26-
      unit: TWh
      index_col: [2, 3]
      header: 4
      nrows: 10
      ncolumns: 16
      names:
        index:
        - scenario
        - year
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: wind offshore
        offwind-dc-fl-oh: wind offshore
        offwind-dc-fb-r: wind offshore
        offwind-dc-fb-oh: wind offshore
        offwind-ac-fl-r: wind offshore
        offwind-ac-fb-r: wind offshore
        onwind: wind onshore
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: hydrogen
        h2-fuel-cell: hydrogen
        coal: coal + other fossil
        coal+ccs: coal + other fossil
        lignite: coal + other fossil
        lignite+ccs: coal + other fossil
        oil-heavy: oil
        oil-light: oil
        oil-shale: oil
        gas-ccgt: methane
        gas-ccgt-ccs: methane
        gas-ocgt: methane
        gas-conv: methane
        urban central solid biomass CHP: other non-res
        ror: hydro (exc. pump storage)
        hydro: hydro (exc. pump storage)

    methane_supply:
      table_type: scenario_comparison
      sheet_name: 32-
      unit: TWh
      index_col: 2
      header: [6, 7]
      nrows: 13
      ncolumns: 9
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        Sabatier: synthetic methane (domestic)
        biogas to gas: biomethane (domestic)
        gas: natural gas (import)

    hydrogen_supply:
      table_type: scenario_comparison
      sheet_name: 33-
      unit: TWh
      index_col: 2
      header: [4, 5]
      nrows: 13
      ncolumns: 9
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        H2 Electrolysis: p2g
        H2 import LH2: ammonia imports
        H2 import Pipeline: low carbon imports
        SMR: smr (grey)
        SMR CC: smr with ccs (blue)

    biomass_supply:
      table_type: scenario_comparison
      sheet_name: 59-
      unit: TWh
      index_col: 2
      header: [4, 5]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        solid biomass: biomass

    energy_imports:
      table_type: scenario_comparison
      sheet_name: 60-
      unit: TWh
      index_col: 2
      header: [3, 4]
      names:
        index:
        - carrier
        column:
        - scenario
        - year
      mapping:
        H2 import LH2: hydrogen
        H2 import Pipeline: hydrogen
        coal: solids
        lignite: solids
        oil primary: liquids
        gas: methane

    generation_profiles:
      table_type: time_series
      sheet_name:
        DE: 30a
        GA: 30b
      unit: GW
      index_col: 1
      header: 4
      names:
        index:
        - snapshot
        column:
        - carrier
      mapping:
        offwind-dc-fl-r: offshore wind
        offwind-dc-fl-oh: offshore wind
        offwind-dc-fb-r: offshore wind
        offwind-dc-fb-oh: offshore wind
        offwind-ac-fl-r: offshore wind
        offwind-ac-fb-r: offshore wind
        onwind: onshore wind
        solar-pv-rooftop: solar
        solar-pv-utility: solar
        h2-ccgt: methane&hydrogen
        h2-fuel-cell: methane&hydrogen
        gas-ccgt: methane&hydrogen
        gas-ccgt-ccs: methane&hydrogen
        gas-ocgt: methane&hydrogen
        gas-conv: methane&hydrogen
        coal: coal&lignite&oil
        coal+ccs: coal&lignite&oil
        lignite: coal&lignite&oil
        lignite+ccs: coal&lignite&oil
        oil: coal&lignite&oil
        oil-heavy: coal&lignite&oil
        oil-light: coal&lignite&oil
        oil-shale: coal&lignite&oil
        battery discharger: battery
        home battery discharger: battery
        urban central solid biomass CHP: other res
        PHS: hydro
        ror: hydro
