# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

# This file is a TEMPLATE for private configuration options that shall not be tracked and only meant for local use.
# To use these options in your local repository, please create a local `config/config.yaml` file which is by default
# untracked and add your required private settings from below.

remote:
  ssh: ''
  path: ''

# Note that a local gurobi.lic file takes precedence over this setting. Please remove for the settings to take effect.
solving:
  solver_options:
    gurobi-default:
      env:
        WLSACCESSID: ''
        WLSSECRET: ''
        LICENSEID:
