# SPDX-FileCopyrightText: Open Energy Transition gGmbH
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: "tyndp"

# TODO set foresight
foresight: myopic

tyndp_scenario: DE  # NT, DE or GA

scenario:
  clusters:
  - all
  planning_horizons:
  - 2030
  - 2040

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'CY', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']

snapshots:
  # TODO define multiple climatic years, being either 1995 2008 or 2009
  start: "2013-01-01"
  end: "2014-01-01"

co2_budget:
  # TODO define carbon budget compliant with EU 2030 and 2050 targets
  2020: 0.720 # average emissions of 2019 to 2021 relative to 1990, CO2 excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
  2025: 0.648 # With additional measures (WAM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
  2030: 0.450 # 55% reduction by 2030 (Ff55)
  2035: 0.250
  2040: 0.100 # 90% by 2040
  2045: 0.050
  2050: 0.000 # climate-neutral by 2050

electricity:
  base_network: tyndp

  # TODO: remove redundant onwind and solar from renewable_carriers list once technologies are included as tyndp_renewable_carriers from PEMMDB data
  renewable_carriers: [solar, solar-hsat, onwind]
  tyndp_renewable_carriers: [hydro, onwind, solar-pv-utility, solar-pv-rooftop, offwind-ac-fb-r, offwind-ac-fl-r, offwind-dc-fb-r, offwind-dc-fl-r, offwind-dc-fb-oh, offwind-dc-fl-oh, offwind-h2-fb-oh, offwind-h2-fl-oh]

  pecd_renewable_profiles:
    enable: true
    fill_gaps_method: zero
    # Complete PECD data is only available for the years 2030, 2040
    # TODO: adjust once udpated 2050 PECD data is available
    available_years:
    - 2030
    - 2040
    technologies:
      Wind_Offshore:
      - offwind-ac-fb-r
      - offwind-ac-fl-r
      - offwind-dc-fb-r
      - offwind-dc-fl-r
      - offwind-dc-fb-oh
      - offwind-dc-fl-oh
      - offwind-h2-fb-oh
      - offwind-h2-fl-oh
      LFSolarPVRooftop:
      - solar-pv-rooftop
      LFSolarPVUtility:
      - solar-pv-utility
      Wind_Onshore:
      - onwind

  pemmdb_hydro_profiles:
    enable: true
    available_years:
    - 2030
    - 2040
    - 2050
    technologies:
    - Run of River
    - Pondage
    - Reservoir
    - PS Open
    - PS Closed

  estimate_renewable_capacities:
    # NOTE: technologies that are covered by TYNDP renewable carriers need to be removed from estimation
    technologies:
    - Onshore
    - PV

  transmission_limit: v1.0

links:
  p_max_pu: 1.0
  p_min_pu: 0

transmission_projects:
  enable: true
  include:
    tyndp2020: false
    nep: false
    manual: false

load:
  source: tyndp # opsd, tyndp
  fill_gaps:
    enable: false
  available_years_tyndp:
  - 2030
  - 2040
  - 2050
  manual_adjustments: false
  supplement_synthetic: false

pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  StorageUnit:
  - PHS
  - hydro
  Store: []

sector:
  transport: false
  heating: false
  biomass: true
  industry: true
  use_industry_load: false
  shipping: false
  aviation: false
  agriculture: false
  fossil_fuels: true

  land_transport_fuel_cell_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:  # Not modelled
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  oil_boilers: false
  biomass_boiler: false
  hydrogen_fuel_cell: false
  ATR: false
  regional_co2_sequestration_potential:
    enable: false
  co2_spatial: false
  co2_network: false
  methanol:
    methanol_to_power:
      ocgt: false
    biomass_to_methanol: false
  ammonia: false
  h2_topology_tyndp: true
  gas_network: false
  electrobiofuels: false
  transmission_efficiency:
    enable:
    - gas pipeline
  imports:
    enable: true
    carriers:
    - H2
  offshore_hubs_tyndp:
    enable: true
    max_capacity:
      DC_OH: 10
      H2 pipeline OH: 30

costs:
  overwrites:
    lifetime:
      electrolysis: 25
      HVDC submarine: 25
      H2 (g) submarine pipeline: 25
      offwind: 25
    efficiency:
      electrolysis: 0.68  # ToDo Account for time-varying efficiencies, currently using fixed 2020 value from TYNDP 2024

clustering:
  mode: administrative
  administrative:
    level: bz
  build_bidding_zones:
    remove_islands: true
    aggregate_to_tyndp: true
  temporal:
    resolution_sector: 6H

plotting:
  balance_map:
    imports_as_flows: true
    bus_carriers:
    - AC
    - H2
    - gas
    - oil
    - methanol
    - co2 stored
    H2:
      bus_factor: 0.005
      branch_factor: 0.04
      flow_factor: 25
